config/routes.rb
Rails.application.routes.draw do

  resources :sections
  resources :pages
  resources :subjects

  devise_for :admin_users

  root 'public#index'
  get '/public/pages/:subject_id', to: 'public#pages'
  get '/public/pages/:subject_id/sections/:page_id', to: 'public#sections'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  # Associations (are always instance methods)
  belongs_to :subject
  has_many :sections

  # Validations
  validates :name, presence: true
  validates :subject, presence: true

  # Named scopes (are always class methods)
  scope :published, -> { where(visible: true) }

  # Callbacks (are always instance methods)
  after_save :update_parent_subject

  private

    def update_parent_subject
      # self.subject.update_attributes(updated_at: Time.now)
      self.subject.touch
    end
end

app/models/section.rb
class Section < ApplicationRecord
  # Associations
  belongs_to :page

  # Validations
  validates :name, presence: true
  validates :position, presence: true

  # Named scopes
  scope :published, -> { where(visible: true) }
end

app/models/subject.rb
class Subject < ApplicationRecord
  # Associations
  has_many :pages, dependent: :delete_all

  # Validations
  validates :name, presence: true, uniqueness: true
  validates :position, presence: true

  # Named scopes
  scope :published, -> { where(visible: true) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin_user!
  layout :layout_by_resource

  private
  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:name, :permalink, :position, :visible, :subject_id)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  skip_before_action :authenticate_admin_user!
  before_action :set_subjects

  layout "public"

  def index
  end

  def pages
    @subject = Subject.find(params[:subject_id])
  end

  def sections
    @subject = Subject.find(params[:subject_id])
    @page = Page.find(params[:page_id])
  end

  protected

    def set_subjects
      @subjects = Subject.published
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:page_id, :name, :content_type, :content, :visible, :position)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @subjects = Subject.all
    respond_to do |format|
      format.json { render json: @subjects }
      format.html
    end
  end

  def show
    @sub = Subject.find(params[:id])
    respond_to do |format|
      format.json { render json: @sub }
      format.html
    end
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      redirect_to subjects_path
    else
      render 'new'
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update_attributes(subject_params)
      redirect_to subjects_path
    else
      render 'edit'
    end
  end

  def destroy
    @subject = Subject.find(params[:id])
    if @subject.destroy
      redirect_to subjects_path
    end
  end

  protected

    def subject_params
      params.require(:subject).permit(:name, :position, :visible)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_visibility_status visible
    status = visible ? "Published" : "Draft"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/public_helper.rb
module PublicHelper
  def is_active_page? page_id, current_page_id
    page_id.to_s == current_page_id ? "active" : ""
  end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #f9a825;">
      <div class="container">
        <%= link_to "Simple CMS", subjects_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Subjects", subjects_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Pages", pages_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Sections", sections_path, class: 'nav-link' %>
            </li>
          </ul>
        </div>
        <%= link_to "Logout", destroy_admin_user_session_path, class: 'logout-link', method: 'delete' %>
      </div>
    </nav>
    <div class="container content">
      <% if notice.present? %>
        <p class="alert alert-primary"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-warning"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container content">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Cms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
        <a class="navbar-brand" href="/">Simple CMS</a>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <% @subjects.each do |subject| %>
              <li class="nav-item active">
                <%= link_to subject.name, "/public/pages/#{subject.id}", class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container content">
      <% if notice.present? %>
        <p class="alert alert-primary"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-warning"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |f| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :subject_id %>
    <%= f.select :subject_id, options_for_select(Subject.all.map { |e| [e.name, e.id] }), {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :permalink %>
    <%= f.text_field :permalink, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :position %>
    <%= f.number_field :position, class: 'form-control' %>
  </div>

  <div class="form-group form-check">
    <%= f.check_box :visible, class: 'form-check-input' %>
    <%= f.label :visible, class: 'form-check-label' %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: 'btn btn-primary' %>
    <%= link_to "Cancel", pages_path, class: 'btn' %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">Edit Page</div>
      <div class="card-body">
        <%= render 'form', page: @page %>
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header d-flex">
        <span class="flex-grow-1">Pages</span>
        <%= link_to 'Add New Page', new_page_path, class: 'btn btn-primary' %>
      </div>
      <table  class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Permalink</th>
            <th>Position</th>
            <th>Visible</th>
            <th>Subject</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @pages.each do |page| %>
            <tr>
              <td><%= page.name %></td>
              <td><%= page.permalink %></td>
              <td><%= page.position %></td>
              <td><%= get_visibility_status(page.visible) %></td>
              <td><%= page.subject.name %></td>
              <td><%= link_to 'Show', page %></td>
              <td><%= link_to 'Edit', edit_page_path(page) %></td>
              <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/pages/new.html.erb
<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">New Page</div>
      <div class="card-body">
        <%= render 'form', page: @page %>
      </div>
    </div>
  </div>
</div>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @page.name %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @page.permalink %>
</p>

<p>
  <strong>Position:</strong>
  <%= @page.position %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @page.visible %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @page.subject %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/sections/_form.html.erb
<%= form_with(model: section, local: true) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.select :page_id, options_for_select(Page.all.map { |e| [e.name, e.id] }, section.page_id), {}, { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= form.label :content_type %>
    <%= form.text_field :content_type, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :visible %>
    <%= form.check_box :visible %>
  </div>
  <div class="form-group">
    <%= form.label :position %>
    <%= form.number_field :position, class: 'form-control' %>
  </div>
  <br />
  <%= form.submit "Save", class: 'btn btn-primary' %>
  <%= link_to "Cancel", sections_path, class: 'btn' %>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

app/views/sections/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header d-flex">
        <span class="flex-grow-1">Sections</span>
        <%= link_to 'Add New Section', new_section_path, class: 'btn btn-primary' %>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Page</th>
            <th>Visible</th>
            <th>Position</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @sections.each do |section| %>
            <tr>
              <td><%= section.name %></td>
              <td><%= section.page.name %></td>
              <td><%= get_visibility_status(section.visible) %></td>
              <td><%= section.position %></td>
              <td><%= link_to 'Show', section %></td>
              <td><%= link_to 'Edit', edit_section_path(section) %></td>
              <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/sections/new.html.erb
<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">New section</div>
      <div class="card-body">
        <%= render 'form', section: @section %>
      </div>
    </div>
  </div>
</div>

app/views/sections/show.html.erb
<p>
  <strong>Page:</strong>
  <%= @section.page.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @section.name %>
</p>

<p>
  <strong>Content type:</strong>
  <%= @section.content_type %>
</p>

<p>
  <strong>Content:</strong>
  <%= @section.content %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @section.visible %>
</p>

<p>
  <strong>Position:</strong>
  <%= @section.position %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>

app/views/subjects/edit.html.erb
<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">Edit Subject: <%= @subject.name %></div>
      <div class="card-body">
        <%= form_for(@subject) do |f| %>

          <% if @subject.errors.any? %>
            <ul class="form-errors">
              <% @subject.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          <% end %>

          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :position %>
            <%= f.number_field :position, class: 'form-control' %>
          </div>
          <div class="form-group form-check">
            <%= f.check_box :visible, class: 'form-check-input' %>
            <%= f.label :visible, class: 'form-check-label' %>
          </div>
          <%= f.submit "Save", class: 'btn btn-primary' %>
          <%= link_to "Cancel", subjects_path, class: 'btn' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/subjects/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header d-flex">
        <span class="flex-grow-1">Subjects</span>
        <%= link_to 'Add New Subject', new_subject_path, class: 'btn btn-primary' %>
      </div>
      <table class="table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Visible</th>
              <th>Position</th>
              <th colspan="3">Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @subjects.each do |sub| %>
              <tr>
                <td><%= sub.id %></td>
                <td><%= sub.name %></td>
                <td>
                  <%= get_visibility_status(sub.visible) %>
                </td>
                <td><%= sub.position %></td>
                <td>
                  <%= link_to 'Show', subject_path(sub) %>
                </td>
                <td>
                  <%= link_to 'Edit', edit_subject_path(sub) %>
                </td>
                <td>
                  <%= link_to 'Delete', subject_path(sub), method: :delete %>
                </td>
              </tr>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>
</div>

app/views/subjects/new.html.erb
<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">New subject</div>
      <div class="card-body">
        <%= form_for(@subject) do |f| %>

          <% if @subject.errors.any? %>
            <ul class="form-errors">
              <% @subject.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          <% end %>

          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :position %>
            <%= f.number_field :position, class: 'form-control' %>
          </div>
          <div class="form-group form-check">
            <%= f.check_box :visible, class: 'form-check-input' %>
            <%= f.label :visible, class: 'form-check-label' %>
          </div>
          <br />
          <%= f.submit "Save", class: 'btn btn-primary' %>
          <%= link_to "Cancel", subjects_path, class: 'btn' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/subjects/show.html.erb
<h4><%= @sub.name %></h4>
Status:
<%= get_visibility_status(@sub.visible) %>
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header d-flex">
        Pages
      </div>
      <table  class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Permalink</th>
            <th>Position</th>
            <th>Visible</th>
          </tr>
        </thead>
        <tbody>
          <% @sub.pages.each do |page| %>
            <tr>
              <td><%= page.name %></td>
              <td><%= page.permalink %></td>
              <td><%= page.position %></td>
              <td><%= page.visible %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>